pipeline:
  build:
    image : python:3.5.2
    commands:
      - pip install Flask
    when:
      event: push
  ssh-deploy:
    image: appleboy/drone-ssh
    pull: true
    host: ${HOST}
    user: ${USER}
    key: ${SSH_KEY}
    port: 22
    command_timeout: 180
    script:
      - cd /root/flask_docker/
      - docker run -dti -p 8001:8001 flask_image
    when:
      event: push
